### ISSUE TITLE
Announcing omission

### ISSUE THREAD

**Issue by ribbleman** [davwheat/rail-announcements#255] opened 2024-07-14 18:33 UTC
When I accessed announcements from Liverpool Central to Southport, one station was omitted. Between Seaforth & Litherland and Blundellsands & Crosby is Waterloo. It is shown on the scrolling display but missing from the audio.

**Comment by davwheat** [comment] 2024-07-14 18:38
Duplicate of #209

**Closed by davwheat** 2024-07-14 18:38 UTC
