### ISSUE TITLE
Live announcements are announced too early if host timezone is ahead

### ISSUE THREAD

**Issue by Dionysusnu** [davwheat/rail-announcements#71] opened 2023-12-13 06:29 UTC
Trains are announced as soon as they appear from the 30-minute-ahead API calls if the host timezone is ahead of British time.

https://github.com/davwheat/rail-announcements/blob/b7ec9a5b0fb8bc3d1ce54d580b355a1542c9ef78/src/announcement-data/systems/stations/AmeyPhil.tsx#L4948 The code constructs a `Date` from the `s.etd`, which looks like `2023-12-13T06:15:00`. Since the timezone specifier is absent, it is interpreted in the host's local timezone. Therefore, the Date ends up offset from the train's actual departure by `(local timezone offset - UK timezone offset)`.

A train leaving in the UK at 06:15 would appear in the API around 05:45 UK time. For a CET host, that would be at 06:45 local time. It then compares 06:15 to 06:45, and since that is less than 4 minutes ahead (in fact, 30 minutes in the past), the announcement is played immediately, even though the train's actual departure is still 30 minutes ahead.

I can see two obvious solutions to this:
- Add an explicit timezone specifier to the API response's time field(s)
- Offset the "current time" Date with the difference between local (host) time and UK time

I'd be happy to contribute a fix, just let me know the preferred solution if so.

**Comment by brodyFlannigan** [comment] 2023-12-14 18:40
I'm having this issue too. I'm in Canada, on Eastern Standard Time.

What I'm seeing in the logs is that trains that are less than 4 minutes away are being marked as "more than 4 minutes away" since my system clock is 5 hours behind UK time.

This does appear to be a regression, as I was not having this issue previously (I can recall everything working properly about a month ago, but not sure of the exact date when the announcements stopped working.)

I will note that delay/cancellation announcements do work properly, just not the "Platform 1 for the 18:33 service to London Paddington..." announcements.

**Comment by davwheat** [comment] 2023-12-17 23:37
Yeah, this is going to be because I moved to the staff departures endpoint of my API from the basic one. This has made my life A LOT easier with regards to getting proper date-time data for estimated arrival/departure, as well as separate arrival/departure times and the raw disruption data behind services.

The downside is that those date-time values don't have a timezone attached.

My understanding is that Huxley2 (the JSON-SOAP intermediary for Darwin data that I use) tries to be relatively transparent with the data it passes down, so adding the TZ there wouldn't be a great idea.

My other solution would have been to add it locally into API responses as part of the data parsing/filtering. This is probably better done with something like day.js rather than trying to use native JS APIs.

**Comment by davwheat** [comment] 2024-01-07 01:33
https://github.com/davwheat/uk-dot-matrix/blob/6f1612f5185ae6b0d0f39b8a944154ad7d1e690a/src/components/displays/NewGTR/TrainServices.tsx#L16-L19

https://github.com/davwheat/uk-dot-matrix/blob/6f1612f5185ae6b0d0f39b8a944154ad7d1e690a/src/components/displays/NewGTR/TrainServices.tsx#L246-L254

This is how I'm trying to prevent this issue in the upcoming changes for my dot matrix board.

**Comment by davwheat** [comment] 2024-01-26 12:24
I believe this should have been fixed during various changes I've made. Let me know if this happens again!

**Comment by Dionysusnu** [comment] 2024-01-28 19:29
When I currently visit https://railannouncements.co.uk/amey-live-train-announcements/, trains are still announced up to ~20 minutes ahead. I have tried reloading with CTRL+F5 to clear the cache, but the same behaviour remains.

**Comment by davwheat** [comment] 2024-01-28 20:33
But the docs do also say that `setDefault` should work: https://day.js.org/docs/en/timezone/set-default-timezone#docsNav

Do services also disappear off the departure board early too, or just get announced early?

**Comment by Dionysusnu** [comment] 2024-01-28 20:37
That page seems to talk specifically about the `dayjs.tz` constructor? So it sets the default for that, but not for `dayjs()` itself.
The departure board looks to be correct, though I've only looked at it now. I've not tested if it stays accurate when running for a longer time.

**Closed** 2024-04-04 15:21 UTC
Labels: bug

**Comment by davwheat** [comment] 2024-04-04 15:27
I think this one should be sorted now based on my testing while travelling in Europe this week.
